attributes:
  metadata:
    label: "Custom Resources Plugin"
  yaml:
    label: 'Resources list (yaml)'
    description: 'List of puppet resources in YAML format'
    weight: 20
    type: "textarea"
    validate: "yaml"
    value: |
      - type: notify
        node_roles: ['(.*)?controller']
        hash:
          'this-is-controller':
            message: 'this is controller'
  yaml_data:
    label: 'Resources list file (yaml)'
    description: 'File with the list of puppet resources in YAML format'
    weight: 30
    type: "file"
    value: "---"
